apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: udagram-reverseproxy
        image: zareen11/udagram-reverseproxy:v1
        command: ["sleep", "infinity"]
        ports:
        - containerPort: 8080